/*******************************************************************************
// Registering native routines (entry points in compiled code)
// 
// Based on code generated by
// R-4.0.3> tools::package_native_routine_registration_skeleton("..", character_only = FALSE)
// for surveillance 1.19.1
// + adding R_forceSymbols(dll, TRUE);
// + adding function declarations via cproto -I/usr/share/R/include -e *.c
*******************************************************************************/

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .C calls */
extern void glr_cusum(int *x, double *mu0, int *lx_R, int *n0_R, double *c_ARL_R, int *ret_N, double *ret_glr, double *ret_cases, int *dir_R, int *ret_R);
extern void glr_cusum_window(int *x, double *mu0, int *lx_R, int *M_R, int *Mtilde_R, double *c_ARL_R, int *ret_N, double *ret_glr, double *ret_cases, int *dir_R, int *ret_R);
extern void glr_epi_window(int *x, double *mu0, int *lx_R, int *Mtilde_R, int *M_R, double *xm10, double *c_ARL_R, int *ret_N, double *ret_glr);
extern void glr_nbgeneral_window(int *x, double *mu0, double *alpha_R, int *lx_R, int *Mtilde_R, int *M_R, double *xm10, double *c_ARL_R, int *ret_N, double *ret_glr, int *dir_R);
extern void glr_nb_window(int *x, double *mu0, double *alpha_R, int *lx_R, int *Mtilde_R, int *M_R, double *c_ARL_R, int *ret_N, double *ret_glr, int *dir_R);
extern void lr_cusum(int *x, double *mu0, int *lx_R, double *kappa_R, double *c_ARL_R, int *ret_N, double *ret_lr, double *ret_cases, int *ret_R);
extern void lr_cusum_nb(int *x, double *mu0, double *alpha_R, int *lx_R, double *kappa_R, double *c_ARL_R, int *ret_N, double *ret_lr, double *ret_cases, int *ret_R);
extern void pkolmogorov2x(double *x, Sint *n);
extern void pkstwo(Sint *n, double *x, double *tol);
extern void siaf_polyCub1_iso(double *x, double *y, int *L, int *intrfr_code, double *pars, int *subdivisions, double *epsabs, double *epsrel, int *stop_on_error, double *value, double *abserr, int *neval);

extern void SRspacetime(double *x, double *y, double *t, int *n, double *radius,
                        double *epsilon, double *areaA, double *areaAcapBk,
                        int *cusum, double *threshold, 
                        double *Rarray, int *idxFirstAlarm, int *idxClusterCenter);
extern void twins(int *x_ptr, int *n_ptr, int *I_ptr,
                  char **logFile_ptr, char **logFile2_ptr, 
                  int *burnin_ptr, int *filter_ptr, int *sampleSize_ptr, 
                  double *alpha_xi_ptr, double *beta_xi_ptr, 
                  int *T_ptr, int *nfreq_ptr, double *psiRWSigma_ptr,
                  double *alpha_psi_ptr, double *beta_psi_ptr,	int *nu_trend_ptr);

/* .Call calls */
extern SEXP determineSources(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
extern SEXP eq3a(SEXP, SEXP, SEXP);

static const R_CMethodDef CEntries[] = {
    {"glr_cusum",            (DL_FUNC) &glr_cusum,            10},
    {"glr_cusum_window",     (DL_FUNC) &glr_cusum_window,     11},
    {"glr_epi_window",       (DL_FUNC) &glr_epi_window,        9},
    {"glr_nbgeneral_window", (DL_FUNC) &glr_nbgeneral_window, 11},
    {"glr_nb_window",        (DL_FUNC) &glr_nb_window,        10},
    {"lr_cusum",             (DL_FUNC) &lr_cusum,              9},
    {"lr_cusum_nb",          (DL_FUNC) &lr_cusum_nb,          10},
    {"pkolmogorov2x",        (DL_FUNC) &pkolmogorov2x,         2},
    {"pkstwo",               (DL_FUNC) &pkstwo,                3},
    {"siaf_polyCub1_iso",    (DL_FUNC) &siaf_polyCub1_iso,    12},
    {"SRspacetime",          (DL_FUNC) &SRspacetime,          13},
    {"twins",                (DL_FUNC) &twins,                16},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"determineSources", (DL_FUNC) &determineSources, 6},
    {"eq3a",             (DL_FUNC) &eq3a,             3},
    {NULL, NULL, 0}
};

void R_init_surveillance(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    R_forceSymbols(dll, TRUE);
}
