/*******************************************************************************
// Registering native routines (entry points in compiled code)
// 
// This code has been generated by
// R-3.4.1> tools::package_native_routine_registration_skeleton("..")
// for surveillance 1.14.0
*******************************************************************************/

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* .C calls */
extern void C_siaf_polyCub1_iso(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void glr_cusum(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void glr_cusum_window(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void glr_epi_window(void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void glr_nbgeneral_window(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void glr_nb_window(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void lr_cusum(void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void lr_cusum_nb(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void pkolmogorov2x(void *, void *);
extern void pkstwo(void *, void *, void *);
extern void SRspacetime(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void twins(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);

/* .Call calls */
extern SEXP eq3a(SEXP, SEXP, SEXP);
extern SEXP _surveillance_determineSourcesC(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CMethodDef CEntries[] = {
    {"C_siaf_polyCub1_iso",  (DL_FUNC) &C_siaf_polyCub1_iso,  12},
    {"glr_cusum",            (DL_FUNC) &glr_cusum,            10},
    {"glr_cusum_window",     (DL_FUNC) &glr_cusum_window,     11},
    {"glr_epi_window",       (DL_FUNC) &glr_epi_window,        9},
    {"glr_nbgeneral_window", (DL_FUNC) &glr_nbgeneral_window, 11},
    {"glr_nb_window",        (DL_FUNC) &glr_nb_window,        10},
    {"lr_cusum",             (DL_FUNC) &lr_cusum,              9},
    {"lr_cusum_nb",          (DL_FUNC) &lr_cusum_nb,          10},
    {"pkolmogorov2x",        (DL_FUNC) &pkolmogorov2x,         2},
    {"pkstwo",               (DL_FUNC) &pkstwo,                3},
    {"SRspacetime",          (DL_FUNC) &SRspacetime,          13},
    {"twins",                (DL_FUNC) &twins,                16},
    {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
    {"eq3a",                            (DL_FUNC) &eq3a,                            3},
    {"_surveillance_determineSourcesC", (DL_FUNC) &_surveillance_determineSourcesC, 6},
    {NULL, NULL, 0}
};

void R_init_surveillance(DllInfo *dll)
{
    R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
