// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// determineSourcesC
List determineSourcesC(NumericVector eventTimes, NumericVector eps_t, NumericMatrix eventCoords, NumericVector eps_s, IntegerVector eventTypes, LogicalMatrix qmatrix);
RcppExport SEXP _surveillance_determineSourcesC(SEXP eventTimesSEXP, SEXP eps_tSEXP, SEXP eventCoordsSEXP, SEXP eps_sSEXP, SEXP eventTypesSEXP, SEXP qmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eventTimes(eventTimesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eps_t(eps_tSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eventCoords(eventCoordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eps_s(eps_sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type eventTypes(eventTypesSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type qmatrix(qmatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(determineSourcesC(eventTimes, eps_t, eventCoords, eps_s, eventTypes, qmatrix));
    return rcpp_result_gen;
END_RCPP
}
