# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

determineSourcesC <- function(eventTimes, eps_t, eventCoords, eps_s, eventTypes, qmatrix) {
    .Call('_surveillance_determineSourcesC', PACKAGE = 'surveillance', eventTimes, eps_t, eventCoords, eps_s, eventTypes, qmatrix)
}

